version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      -.:/src/java
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:

    build: 
      context: .
      dockerfile: src/main/java/server/dockerfile
    ports:
      - "27017:27017"
